services:
  hd_wallet_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hd_wallet_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app

  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongo_db
    ports:
      - "8081:8081"
    env_file:
      - .env
      
volumes:
  mongo-data:
